export const ROLES = {
  READER: "READER",
  CREATOR: "CREATOR",
  AUTHOR: "AUTHOR",
  VIP_GOLD: "VIP_GOLD",
  PREMIUM_CREATOR: "PREMIUM_CREATOR",
  ADMIN: "ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
} as const

export const ROLE_HIERARCHY: Record<string, number> = {
  READER: 0,
  CREATOR: 1,
  AUTHOR: 2,
  VIP_GOLD: 3,
  PREMIUM_CREATOR: 4,
  ADMIN: 5,
  SUPER_ADMIN: 6,
}

export const AUTH_ROLES = [ROLES.ADMIN, ROLES.SUPER_ADMIN] as const
export const AUTHOR_ROLES = [ROLES.AUTHOR, ROLES.VIP_GOLD, ROLES.PREMIUM_CREATOR, ROLES.ADMIN, ROLES.SUPER_ADMIN] as const
export const CREATOR_ROLES = [ROLES.CREATOR, ROLES.PREMIUM_CREATOR, ROLES.ADMIN, ROLES.SUPER_ADMIN] as const

export const FREE_EPISODES_PER_DAY = 2
export const WAIT_EPISODE_THRESHOLD = 20
export const VIP_UNLOCK_COOLDOWN_HOURS = 24
export const OTP_EXPIRY_MS = 600_000
export const OTP_RESEND_COOLDOWN_MS = 30_000

export const SUBSCRIPTION_PRICES = {
  MONTHLY: 999,
  YEARLY: 7999,
} as const

export const TOPUP_AMOUNTS = [500, 1000, 2000, 5000] as const

export const CACHE_TTL = {
  USER_PROFILE: 300,
  STORY_LIST: 300,
  STORY_DETAIL: 600,
  EPISODE: 600,
  READING_PROGRESS: 60,
  DAILY_LIMIT: 60,
} as const
